### ISSUE TITLE
AttributeError: module 'rados' has no attribute 'Rados'

### ISSUE THREAD

**Issue by guoqiao** [ricardoasmarques/ceph-dev-docker#126]
Hi, 

I am trying to setup a ceph dev env,  and found this repo via https://insujang.github.io/2020-11-03/deploying-a-ceph-development-environment-cluster/

It is very helpful,  thank you.

However, at step "4. Ceph Dashboard", I got:

```
╭─root@ceph-dev /ceph ‹master› 
╰─# npm-start.sh 
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
Traceback (most recent call last):
  File "./bin/ceph", line 1318, in <module>
    retval = main()
  File "./bin/ceph", line 978, in main
    conffile = rados.Rados.DEFAULT_CONF_FILES
AttributeError: module 'rados' has no attribute 'Rados'
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
.["/api/"].target=                 
jq: 1 compile error
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
.["/ui-api/"].target=                    
jq: 1 compile error
```

`ceph -s` also report same error:

```
╭─root@ceph-dev /ceph/build ‹master› 
╰─# bin/ceph -s
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
Traceback (most recent call last):
  File "bin/ceph", line 1318, in <module>
    retval = main()
  File "bin/ceph", line 978, in main
    conffile = rados.Rados.DEFAULT_CONF_FILES
AttributeError: module 'rados' has no attribute 'Rados'
```

It seems the rados module has updated and break the code ?

**Comment by p-se** [comment]
hi @guoqiao, while I don't know if that'll fix your issue, it seems that this repo has been moved into the SUSE organization under https://github.com/suse/ceph-dev-docker. The fork there is now being more actively development than this one.

**Comment by votdev** [comment]
@ricardoasmarques Maybe you should consider putting this repo into archive mode and redirect to https://github.com/suse/ceph-dev-docker in the README.md (e.g. like we did that for [openattic](https://github.com/openattic/openattic)).
