### ISSUE TITLE
Errors occurred during compling ceph

### ISSUE THREAD

**Issue by kristol07** [ricardoasmarques/ceph-dev-docker#56]
Hi, after following the steps in the documentation, I have now a running container. 

But when I try to build the ceph using setup-ceph.sh script, it fails.

The error message is below:

``txt
git version 2.20.1
WITH_PYTHON 3
-- Building with ccache: /usr/bin/ccache, CCACHE_DIR=
-- NSS_LIBRARIES: /usr/lib64/libssl3.so;/usr/lib64/libsmime3.so;/usr/lib64/libnss3.so;/usr/lib64/libnssutil3.so
-- NSS_INCLUDE_DIRS: /usr/include/nss3
 '--host=x86_64-suse-linux-gnu' '--build=x86_64-suse-linux-gnu' '--program-prefix=' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/lib' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-dependency-tracking' '--enable-ipv6' '--with-ssl' '--with-ca-fallback' '--without-ca-path' '--without-ca-bundle' '--with-gssapi=/usr/lib/mit' '--with-libidn2' '--with-libssh' '--with-libmetalink' '--enable-hidden-symbols' '--disable-static' '--enable-threaded-resolver' 'build_alias=x86_64-suse-linux-gnu' 'host_alias=x86_64-suse-linux-gnu' 'CFLAGS=-O2 -Wall  -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIE' 'LDFLAGS= -pie' 'CPPFLAGS=-D_FORTIFY_SOURCE=2'
-- libcurl is linked with openssl: explicitly setting locks
-- ssl soname: libssl.so.1.1
-- crypto soname: libcrypto.so.1.1
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.2", minimum required is "3")
-- BUILDING Boost Libraries at j 2
-- boost will be downloaded...
-- Found Yasm: good -- capable of assembling x86_64
-- Found PythonInterp: /usr/bin/python3 (found version "3.7.2")
-- Setting civetweb to use OPENSSL >= 1.1
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find RabbitMQ (missing: rabbitmq_INCLUDE_DIR rabbitmq_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindRabbitMQ.cmake:9 (find_package_handle_standard_args)
  src/rgw/CMakeLists.txt:182 (find_package)

-- Configuring incomplete, errors occurred!
``

The Cmake error log file is also attached.
[CMakeError.log](https://github.com/ricardoasmarques/ceph-dev-docker/files/2917889/CMakeError.log)

Since I am completely new to cmake and compiling of ceph, it's the error of script or something wrong in the environment relating to Dockerfile? Thanks for any advice and help.

**Comment by LenzGr** [comment]
Yes, this is a known issue. A fix for this should have been merged just recently: https://github.com/ceph/ceph/pull/26667

**Comment by ricardoasmarques** [comment]
@kristol07 this PR fixes your problem https://github.com/ricardoasmarques/ceph-dev-docker/pull/57

**Comment by kristol07** [comment]
@LenzGr @ricardoasmarques  I have pulled the lastest ceph repo this morning, and also checkout to the branch 'disable-rabbitmq' of ceph-dev-docker repo. But when I try to rebuild, new errors come out:

CMake Internal Error (please report a bug) in src/rgw/CMakeLists.txt:
  CMAKE_C_STANDARD_DEFAULT is set to invalid value '17'

Note: The stack trace will not use advanced capabilities because this is a release build.
0x55ae7d4eb6e4 : cmsys::SystemInformationImplementation::GetProgramStack[abi:cxx11](int, int) [(cmake) ???:-1]
0x55ae7d4ec12d : cmsys::SystemInformation::GetProgramStack[abi:cxx11](int, int) [(cmake) ???:-1]
0x55ae7d458087 : displayMessage(cmake::MessageType, std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >&) [(cmake) ???:-1]
0x55ae7d45867b : cmMessenger::DisplayMessage(cmake::MessageType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cmListFileBacktrace const&) const [(cmake) ???:-1]
0x55ae7d1f6fd6 : cmLocalGenerator::AddCompilerRequirementFlag(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cmGeneratorTarget const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [(cmake) ???:-1]
0x55ae7d1f750b : cmLocalGenerator::AddCompileOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cmGeneratorTarget*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [(cmake) ???:-1]
0x55ae7d1fb501 : cmLocalGenerator::GetTargetCompileFlags(cmGeneratorTarget*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) [(cmake) ???:-1]
0x55ae7d38583b : cmCommonTargetGenerator::GetFlags(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [(cmake) ???:-1]
0x55ae7d440eea : cmMakefileTargetGenerator::WriteTargetLanguageFlags() [(cmake) ???:-1]
0x55ae7d4573f9 : cmMakefileLibraryTargetGenerator::WriteRuleFiles() [(cmake) ???:-1]
0x55ae7d43beb9 : cmLocalUnixMakefileGenerator3::Generate() [(cmake) ???:-1]
0x55ae7d4089aa : cmGlobalGenerator::Generate() [(cmake) ???:-1]
0x55ae7d415ca3 : cmGlobalUnixMakefileGenerator3::Generate() [(cmake) ???:-1]
0x55ae7d28d54a : cmake::Generate() [(cmake) ???:-1]
0x55ae7d292f80 : cmake::Run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) [(cmake) ???:-1]
0x55ae7d1caefd : do_cmake(int, char const* const*) [(cmake) ???:-1]
0x55ae7d1c210a : main [(cmake) ???:-1]
0x7f6da4f38b7b : __libc_start_main [(libc.so.6) ???:-1]
0x55ae7d1ca31a : _start [(cmake) ???:-1]

This is just an error for rgw, and there are similar error messages for each component under /src directory. 

It seems the compiling is failed because of c++ version?

`╭─root@ceph-dev /shared/bin
╰─# gcc --version
gcc (SUSE Linux) 8.2.1 20190204 [gcc-8-branch revision 268513]
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

╭─root@ceph-dev /shared/bin
╰─# cmake --version
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).`

**Comment by kristol07** [comment]
> @LenzGr @ricardoasmarques I have pulled the lastest ceph repo this morning, and also checkout to the branch 'disable-rabbitmq' of ceph-dev-docker repo. But when I try to rebuild, new errors come out:
> 
> CMake Internal Error (please report a bug) in src/rgw/CMakeLists.txt:
> CMAKE_C_STANDARD_DEFAULT is set to invalid value '17'
> 
> Note: The stack trace will not use advanced capabilities because this is a release build.
> 0x55ae7d4eb6e4 : cmsys::SystemInformationImplementation::GetProgramStack[abi:cxx11](int, int) [(cmake) ???:-1]
> 0x55ae7d4ec12d : cmsys::SystemInformation::GetProgramStack[abi:cxx11](int, int) [(cmake) ???:-1]
> 0x55ae7d458087 : displayMessage(cmake::MessageType, std::__cxx11::basic_ostringstream<char, std::char_traits, std::allocator >&) [(cmake) ???:-1]
> 0x55ae7d45867b : cmMessenger::DisplayMessage(cmake::MessageType, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, cmListFileBacktrace const&) const [(cmake) ???:-1]
> 0x55ae7d1f6fd6 : cmLocalGenerator::AddCompilerRequirementFlag(std::__cxx11::basic_string<char, std::char_traits, std::allocator >&, cmGeneratorTarget const*, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&) [(cmake) ???:-1]
> 0x55ae7d1f750b : cmLocalGenerator::AddCompileOptions(std::__cxx11::basic_string<char, std::char_traits, std::allocator >&, cmGeneratorTarget*, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&) [(cmake) ???:-1]
> 0x55ae7d1fb501 : cmLocalGenerator::GetTargetCompileFlags(cmGeneratorTarget*, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, std::__cxx11::basic_string<char, std::char_traits, std::allocator >&) [(cmake) ???:-1]
> 0x55ae7d38583b : cmCommonTargetGenerator::GetFlags(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&) [(cmake) ???:-1]
> 0x55ae7d440eea : cmMakefileTargetGenerator::WriteTargetLanguageFlags() [(cmake) ???:-1]
> 0x55ae7d4573f9 : cmMakefileLibraryTargetGenerator::WriteRuleFiles() [(cmake) ???:-1]
> 0x55ae7d43beb9 : cmLocalUnixMakefileGenerator3::Generate() [(cmake) ???:-1]
> 0x55ae7d4089aa : cmGlobalGenerator::Generate() [(cmake) ???:-1]
> 0x55ae7d415ca3 : cmGlobalUnixMakefileGenerator3::Generate() [(cmake) ???:-1]
> 0x55ae7d28d54a : cmake::Generate() [(cmake) ???:-1]
> 0x55ae7d292f80 : cmake::Run(std::vector<std::__cxx11::basic_string<char, std::char_traits, std::allocator >, std::allocator<std::__cxx11::basic_string<char, std::char_traits, std::allocator > > > const&, bool) [(cmake) ???:-1]
> 0x55ae7d1caefd : do_cmake(int, char const* const*) [(cmake) ???:-1]
> 0x55ae7d1c210a : main [(cmake) ???:-1]
> 0x7f6da4f38b7b : __libc_start_main [(libc.so.6) ???:-1]
> 0x55ae7d1ca31a : _start [(cmake) ???:-1]
> 
> This is just an error for rgw, and there are similar error messages for each component under /src directory.
> 
> It seems the compiling is failed because of c++ version?
> 
> `╭─root@ceph-dev /shared/bin
> ╰─# gcc --version
> gcc (SUSE Linux) 8.2.1 20190204 [gcc-8-branch revision 268513]
> Copyright (C) 2018 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions. There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> ╭─root@ceph-dev /shared/bin
> ╰─# cmake --version
> cmake version 3.13.4
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).`

Instead of using the given script, I followed directly the build instructions in Ceph documentation:
```sh
./do_cmake.sh
cd build
make
```
The building process is successful without errors. So I think there is a 'bug' in the 'setup-ceph.sh' script?

**Comment by ricardoasmarques** [comment]
I wasn't able to reproduce this second error, so I'm closing the issue.

Feel free to reopen if the problem persists.
