### ISSUE TITLE
change the base image to a more stable one

### ISSUE THREAD

**Issue by mljli** [ricardoasmarques/ceph-dev-docker#88]
openSUSE Tumbleweed is a rolling release so something could easily break after an update. Yesterday I tried to setup a ceph dev environment and encountered the issue openssl/openssl#10015 with the latest opensuse/tumbleweed image. It was caused by openssl 1.1.1d. Maybe we should use a non-rolling update release?

**Comment by LenzGr** [comment]
We use Tumbleweed on purpose, to catch potential regressions/issues early in the process. If you would like to use a more stable release, you can easily switch from `FROM opensuse/tumbleweed` to `FROM opensuse/leap` in the `Dockerfile`.
